loggers:
    system:
      level: debug 
      appender:
          - type: StdLogAppender
            formatter:
              name: PatternLogFormatter
#          - type: FileLogAppender
#            formatter:
#              name: PatternLogFormatter
#   -
#     name: root
#     level: info
#     autoNewLine: 0
#     formatter:
#       - name: patternLogFormatter
#         pattern: "%d{%Y}"
#     appender:
#       - type: StdLogAppender
system:
 ports: [8080, 90, 100]